const PATIENTS_GET_DETAILS_REQUEST = "PATIENTS_GET_DETAILS_REQUEST"
const PATIENTS_GET_DETAILS_SUCCESS = "PATIENTS_GET_DETAILS_SUCCESS"
const PATIENTS_GET_DETAILS_FAILURE = "PATIENTS_GET_DETAILS_FAILURE"

export default {
    PATIENTS_GET_DETAILS_REQUEST,
    PATIENTS_GET_DETAILS_SUCCESS,
    PATIENTS_GET_DETAILS_FAILURE
}