const PATIENTS_GET_DETAILS_REQUEST = "PATIENTS_GET_DETAILS_REQUEST"
const PATIENTS_GET_DETAILS_SUCCESS = "PATIENTS_GET_DETAILS_SUCCESS"
const PATIENTS_GET_DETAILS_FAILURE = "PATIENTS_GET_DETAILS_FAILURE"

const PATIENTS_POST_DETAILS_REQUEST = "PATIENTS_POST_DETAILS_REQUEST"
const PATIENTS_POST_DETAILS_SUCCESS = "PATIENTS_POST_DETAILS_SUCCESS"
const PATIENTS_POST_DETAILS_FAILURE = "PATIENTS_POST_DETAILS_FAILURE"

const PATIENTS_SINGLE_DETAILS_REQUEST  = "PATIENTS_SINGLE_DETAILS_REQUEST "
const PATIENTS_SINGLE_DETAILS_SUCCESS = "PATIENTS_SINGLE_DETAILS_SUCCESS"
const PATIENTS_SINGLE_DETAILS_FAILURE = "PATIENTS_SINGLE_DETAILS_FAILURE"
export default {
    PATIENTS_GET_DETAILS_REQUEST,
    PATIENTS_GET_DETAILS_SUCCESS,
    PATIENTS_GET_DETAILS_FAILURE,

    PATIENTS_POST_DETAILS_REQUEST,
    PATIENTS_POST_DETAILS_SUCCESS,
    PATIENTS_POST_DETAILS_FAILURE,

    PATIENTS_SINGLE_DETAILS_REQUEST,
    PATIENTS_SINGLE_DETAILS_SUCCESS,
    PATIENTS_SINGLE_DETAILS_FAILURE



}